  ---
title: "Figures"
output: html_document
---

Load libraries 
```{r}
library(BiocManager)
library(Biostrings)
library(muscle)
library(ape)
library(readr)
library(dplyr)
library(reshape2)
```

Loading Data 
```{r}
MyData<-read.csv("ChrISequences.csv")
str(MyData)
```

Clean up Data
```{r}
MyData$Sequence<-gsub("[^ATCG]", "", MyData$Sequence)
```

Removing S paradoxus species 
```{r}
MyData2 <- MyData[!grepl("Spar", MyData$X),]
```

Aligning sequences with new data not containing the S paradoxus 
```{r}
DataDNAstring<-DNAStringSet(MyData2$Sequence)
```

```{r}
MyData2$X <- gsub(">", "", MyData2$X)
names(DataDNAstring)<-paste(MyData2$X)
```

```{r}
DataAlign<-muscle::muscle(stringset = DataDNAstring, quiet = T)
```

Distance Matrix
```{r}
DataAlignBin<-as.DNAbin(DataAlign)
DataDM<-dist.dna(DataAlignBin, model = "K80")
```

```{r}
DataDMmat<-as.matrix(DataDM)
dim(DataDMmat)
```


```{r}
DataDat<-melt(DataDMmat)
dim(DataDat)
```

```{r}
library(ggplot2)
```

Distance Matrix 
```{r}
ggplot(data = DataDat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()+scale_fill_gradientn(colours=c("white","blue","green","red")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  xlab("Yeast Strains") + 
  ylab("Yeast Strains") + 
  labs(title = "Distance Matrix of Yeast Strains")
```

```{r}
library(ggtree)
```

```{r}
Tree <- nj(DataDM)
```

```{r}
Info <- read.csv("./ordered_strain_info.csv")
Info <- Info[!Info$Strain == "Spar",]

ggtree(Tree, branch.length = 'none', layout = "circular") %<+% Info + 
  geom_tiplab(aes(colour = Substrate_of_isolation)) 
```
```{r}
Info <- read.csv("./ordered_strain_info.csv")
Info <- Info[!Info$Strain == "Spar",]

ggtree(Tree, branch.length = 'none', layout = "circular") %<+% Info + 
  geom_tree(aes(colour = Substrate_of_isolation)) + 
  labs(title = "Phylogeny of Yeast Strains", colour = "Substrate of Isolation") 
```
```{r}
ggtree(Tree, branch.length = 'none', layout = "circular") %<+% Info + 
  geom_tree(aes(colour = Geographic_location)) + 
  labs(title = "Phylogeny of Yeast Strains", colour = "Geographic Location") 
```

```{r}
ggtree(Tree, branch.length = 'none', layout = "circular") %<+% Info + 
  geom_tree(aes(colour = Phylogeny)) + 
  labs(title = "Phylogeny of Yeast Strains", colour = "Phylogeny") + 
  geom_tiplab()
```
```{r}
ggtree(Tree, branch.length = 'none', layout = "circular") %<+% Info + 
  geom_tree(aes(colour = Genome_data)) + 
  labs(title = "Phylogeny of Yeast Strains", colour = "Genome Data") 
```
```{r}
ggtree(Tree, branch.length = 'none', layout = "circular") %<+% Info + 
  geom_tree(aes(colour = Dataset)) + 
  labs(title = "Phylogeny of Yeast Strains", colour = "Dataset") + 
  geom_tiplab()
```



